strawburry_finance:
    resource: "@StrawburryFinanceBundle/Resources/config/routing.yml"
    prefix:   /

strawburry_user:
    resource: "@StrawburryUserBundle/Resources/config/routing.yml"
    prefix:   /

